services:
  dagster:
    build: .
    container_name: dagster
    ports:
      - "3000:3000"
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    command: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]

  dagster-daemon:
    build: .
    container_name: dagster-daemon
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    command: ["dagster-daemon", "run"]